title: Rama Rama
logo: /assets/image/Rama_Rama.jpg
description: Product Implementation Expert and SME (Payments) for Global PAYPlus (GPP-SP) at Finastra aka D+H (Fundtech) | AI Enthusiast
show_downloads: true
theme: jekyll-theme-minimal
